/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const UniverseLazyImport = createFileRoute('/universe')()
const TodoLazyImport = createFileRoute('/todo')()
const RpsLazyImport = createFileRoute('/rps')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const UniverseLazyRoute = UniverseLazyImport.update({
  id: '/universe',
  path: '/universe',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/universe.lazy').then((d) => d.Route))

const TodoLazyRoute = TodoLazyImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/todo.lazy').then((d) => d.Route))

const RpsLazyRoute = RpsLazyImport.update({
  id: '/rps',
  path: '/rps',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/rps.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/rps': {
      id: '/rps'
      path: '/rps'
      fullPath: '/rps'
      preLoaderRoute: typeof RpsLazyImport
      parentRoute: typeof rootRoute
    }
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoLazyImport
      parentRoute: typeof rootRoute
    }
    '/universe': {
      id: '/universe'
      path: '/universe'
      fullPath: '/universe'
      preLoaderRoute: typeof UniverseLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/rps': typeof RpsLazyRoute
  '/todo': typeof TodoLazyRoute
  '/universe': typeof UniverseLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/rps': typeof RpsLazyRoute
  '/todo': typeof TodoLazyRoute
  '/universe': typeof UniverseLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/rps': typeof RpsLazyRoute
  '/todo': typeof TodoLazyRoute
  '/universe': typeof UniverseLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rps' | '/todo' | '/universe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rps' | '/todo' | '/universe'
  id: '__root__' | '/' | '/rps' | '/todo' | '/universe'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  RpsLazyRoute: typeof RpsLazyRoute
  TodoLazyRoute: typeof TodoLazyRoute
  UniverseLazyRoute: typeof UniverseLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  RpsLazyRoute: RpsLazyRoute,
  TodoLazyRoute: TodoLazyRoute,
  UniverseLazyRoute: UniverseLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/rps",
        "/todo",
        "/universe"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/rps": {
      "filePath": "rps.lazy.tsx"
    },
    "/todo": {
      "filePath": "todo.lazy.tsx"
    },
    "/universe": {
      "filePath": "universe.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
